cloud:
  aws:
    credentials:
      access-key: AKIAZIDT2LDO3W5YSBIN
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: cloudphotosstorage


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090
